commercialhaskell/path

LICENSE, README.md, path.cabal, src/Path.hs
See comment of the second commit.
=> Improve description of the package

.travis.yml, stack.yaml, test/Main.hs
You'll need to switch on the Travis integration in [your Travis profile](https://travis-ci.org/profile/chrisdone).
=> Add Travis CI config

src/Path.hs
Clarified the semantics of a valid or expected path.
=> Update documentation of parsing functions.

src/Path.hs
* make it portable (for windows)
* remove some redundant checks
* minor update to documentation
=> Fix hardcoded path separators (fixes #28)

test/Main.hs
This fixes the tests for the advertised property: `filename (p </> a) == filename a` and adds property tests for it.
=> Fixed filename tests and added a property test

.travis.yml
I'm not sure how to do it for the cabal builds, but this should fix the seed for stack build at least.
=> A fixed seed for tests on travis

path.cabal, test/Main.hs, test/ValidityTest.hs
This does NOT fix #54 yet, but it prepares to fix it as described there.
This commit is separated from the rest of the fix for easier reviewing.
=> Split test suites

lts-7.yaml, path.cabal, test/Main.hs, test/Path/Gen.hs, test/ValidityTest.hs
This is the second port of what was started in #55 and actually fixes #54.
=> Test validity upgrade

appveyor.yml
=> Add basic appveyor.yml

src/Path.hs
@chrisdone Is this ok for you?
This info is just a duplicate of what's in the .cabal file and prone to get outdated.
=> Remove module header

.travis.yml, lts-2.yaml, lts-6.yaml
Please see the commit messages for explanation.
If there's a consensus among the other maintainers for keeping the email notifications disabled I'll concur, but I'd rather have them.
=> Tweak the Travis configuration

path.cabal, test/ValidityTest.hs
=> Marked the validity tests as parallelisable

appveyor.yml, test/Path/Gen.hs, test/ValidityTest.hs
=> Added shrinking to validity tests

lts-2.yaml, lts-6.yaml, path.cabal, stack.yaml, test/Path/Gen.hs, test/ValidityTest.hs
This replaces #86 and should fix #80
=> Old ghc compatibility

CHANGELOG, src/Path.hs, test/Posix.hs, test/ValidityTest.hs, test/Windows.hs
=> Rename isParentOf and stripDir for clarity and consistency

CHANGELOG, src/Path.hs, src/Path/Internal.hs, test/Posix.hs, test/Windows.hs
=> Allow "parent" to work on relative paths as well

CHANGELOG, path.cabal, src/Path.hs, test/Posix.hs
This PR add function that adds file extension according to #105. I'm not sure I did everything right because I didn't notice contribution policies. But I tried. Please, correct me, if I need to add/fix anything.
=> Add `addFileExtension` function and `(<.>)` operator

CHANGELOG, path.cabal, src/Path/Include.hs, test/Common.hs, test/Path/Gen.hs, test/Posix.hs, test/ValidityTest.hs, test/Windows.hs
See the changelog for more details.
=> Make extension operations lawful

src/Path/Internal.hs
This seems uncontroversial to me, but I'm happy to be wrong.
=> Added a data and a generic instance

src/Path/Include.hs
Hi, I use this a lot and it's pretty simple so I wondered if it is in scope of this library.
=> Add changeDir function

src/Path/Internal/Include.hs
EDIT: This description is now outdated, see below.
---
In `template-haskell-2.17.0.0` in GHC 9.0.1, the signature of `lift` changed (see [here](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#overloaded-quotation-brackets)) from 
```haskell
lift :: t -> Q Exp
```
to
```haskell
lift :: Quote m => t -> m Exp 
```
which means that the current instance of `Lift (Path a b)` does not work anymore (as `lookupTypeName :: String -> Q (Maybe Name)`).
As a solution, I simply removed the instance, and moved it into a top-level function `liftPath`, but maybe there are other ways.
Also, this means that this is technically a breaking change, as the `Lift` instance is no longer present.
---
Tested with
```
cabal test -w ghc-9.0.1 --allow-newer='hashable:base,time-compat:base,these:base,assoc:base …
```
=> support GHC 9.0

.github/workflows/ci.yaml
=> also test with GHC 9.0.1 on CI

CHANGELOG, src/Path/Include.hs, test/Path/Gen.hs, test/ValidityTest.hs
=> Add mapSomeBase and prjSomeBase for modifying or projecting SomeBase.
