- test/Main.hs
> test: missing case for parseRelFile

- src/Path.hs
The properties for stripDir and parent used the name 'parent' as a
variable.
The properties for filename and dirname seemed to be wrong and also used
'parent' as a variable.
> Improve a few property definitions

- .gitignore
- src/Path.hs
- src/Path/Internal.hs
Thanks for this library, I use it everywhere now. Most of these edits are completely optional, but type-safe synonyms for `toFilePath` is something I *always* define, simply because I want type-checker “double-check” me when I leave domain of this library and convert things into `FilePath` (which is just a `String` after all). Rationale is: you always know what kind of path you want to convert to `FilePath`, but `toFilePath` will convert *anything* into `FilePath`, even if it happens to be of wrong type (you think about absolute path, but it's relative — not impossible situation unless you put type-signatures for all intermediate transformations), so I don't trust myself, I trust type-checker, hence these synonyms.
----
There are quite a few commits there, how about publishing new release …
> Various improvements

- src/Path.hs
- test/Main.hs
The behaviour is surprising given the rather established meaning of *relative path*.  Since `path` doesn't quite follow that meaning (and for good reasons) the next best thing is clarifying documentation.
> Clarify what limitations the RelX parsers have.

- src/Path.hs
The line was triggering parse error when running haddock:
```
src/Path.hs:16:1:
parse error on input ‘-- | A normalizing well-typed path type.’
```
Removing it works for me.
> Fix a haddock parse error

- .travis.yml
- path.cabal
- test/Main.hs
I ran into https://github.com/lpsmith/bytestring-builder/issues/8 on the way, which might be a recurring issue.
> Add cabal Travis jobs to check compatibility with older ghcs and cutting edge packages

- src/Path.hs
isAbsolute covers the removed check already.
> Remove redundant checks

- path.cabal
- src/Path.hs
- stack.yaml
- test/Main.hs
- test/Path/Gen.hs
This `path` library is very scarsely tested. I would like to improve that.
There are invariants for the `Path` type.
We should:
1. Make those invariants explicit
2. Make sure that all the functions that produce a `Path`, can only produce valid `Path`s.
3. Add a bunch of property tests.
4. Add doctests to show what functions should (intuitively) do
5. Add/Generate a bunch of unit tests to ensure that the API is invariant under refactors/optimisations
(6.) Optimise the internals to use something better than `String`.
This commit just takes the first step by adding a `Validity` instance for `Path`s.
I would like to hear your thoughts on the matter.
See https://github.com/NorfairKing/safepath for the level of testing I would like to achieve here.
> The first step towards validity-based testing.

- test/Path/Gen.hs
This was made as a reply to #37.
This PR makes the validity instances for typed path more strict and exposes some bugs in doing so:
```
$(mkAbsFile "/.") -- DANGEROUS
"/"
$(mkRelFile "a/.") -- Disobeys invariant: file does not end in slash
"a/"
$(mkRelFile "a..") -- Disobeys invariant: no double dot in filepath
"a.."
$(mkRelDir "a../") -- Disobeys invariant: no double dot in filepath
"a../"
```
Fixes are not part of this PR.
> Stricter validity instance that exposes some bugs

- src/Path.hs
Allow to get and set file extension. I'm tired of converting to and form `FilePath` every time I need this.
I tried to follow your naming style, but well, `filext` may be not the best name, let me know if you have a better naming idea.
> Add ‘fileExtension’ and ‘setFileExtension’

- test/Main.hs
This also exposes a potential 'bug':
```
Prelude> :load Path
*Path> :set -XTemplateHaskell
*Path> dirname $(mkAbsDir "/") :: Path Rel Dir
"/"
```
See #33
> Added tests for dirname

- src/Path/Internal.hs
Adds to the haddock descriptions of what "b" and "t" mean.
This is just copied from the readme.
> Explicitly document the type variables of Path

- src/Path/Internal.hs
Using `show` will include double quotes (as usual when `show`ing a `String`) but docs make it sound like the quotes are not included.
> Docs for `show` are misleading

- path.cabal
- test/Main.hs
Close #46.
Also drop redundant denpendencies for test suites and align Cabal file for consistency (could not resist!).
> Add version bounds to dependencies

- .travis.yml
This easier-to-read script uses Cabal for builds. I don't use Cabal, but for CI it may be better because it allows to build in more adverse environment and what builds with Cabal will sure build with Stack and appropriate resolver. I hope this should help catch things like #46 in the future.
This also adds a check that we can generate tarball distribution without issues and that Haddock coverage is 100%.
> Try another Travis script

- appveyor.yml
- stack.yaml
- test/Path/Gen.hs
As this appears to fix the validity-test testsuite, run it in CI
See #41 for the decision to allow linebreaks in paths.
Fixes #37, closes #66.
> Allow linebreaks in Validity instances

- src/Path.hs
- src/Path/Internal.hs
- test/Path/Gen.hs
1) ".." is valid as an infix but valid not as the only path component. For example,
"x/y..y/x" is valid but "x/../x" is not. This fix allows the former case but
rejects the latter.
2) I also merged the ".." case in `hasParentDir`. Though it is not necessary in case of absolute paths, it does no harm either and we have one unified abstraction for all ".." cases.
> Fix validity test when ".." is part of the file or dir name

- CHANGELOG
- README.md
- src/Path.hs
- test/Posix.hs
- test/Windows.hs
Implements #59
I fell in love with this feature request.
This turned out to be a really easy feature to implement,
and it has the advantage of making Path construction shorter.
```haskell
$(mkAbsDir "/home/chris")</> $(mkRelFile "foo.txt")
[absdir|/home/chris|]</>[relfile|foo.txt|]
```
That's a 9 character difference 😄 
This also removes the need for a space after `</>` when it's followed by `$(..)`
> Add QuasiQuoters `absdir`, `reldir`, `absfile`, and `relfile`

- CHANGELOG
- src/Path.hs
- src/Path/Internal.hs
- test/Path/Gen.hs
- test/Posix.hs
- test/ValidityTest.hs
- test/Windows.hs
The discussion thread that I started for empty path finally boils down to this. A quick look at the changes in the tests will give you an idea about what it means to the library user. Let me know what you think about this. These are all the changes needed except for some doc tweaks if this gets accepted.
It essentially allows us to compose "." with other relative paths:
> > toFilePath $ $(mkRelDir "./") </> $(mkRelDir "./")
> > "./"
> > toFilePath $ $(mkRelDir "./") </> $(mkRelDir "x")
> > "x/"
> > toFilePath $ $(mkRelDir "x") </> $(mkRelDir ".")
> > "x/"
Also dirname "." is "." itself:
> > dirname $(mkRelDir ".") == $(mkRelDir ".")
> > True
> Allow . as a relative path

- CHANGELOG
- src/Path.hs
Also:
1) Rename PathParseException and one of its constructors
2) Export the constructors so that info about exceptions can be extracted.
3) Document which specific exception is thrown during each operation.
These are the remaining changes from #35 . These are breaking so should go before the next major version release.
> Rename, export, document exceptions

- README.md
This was not obvious for me from the first read. So I hope that I could save some time of first-starters.
Related to https://github.com/commercialhaskell/path/issues/107
> Added more info where to find resolveDir function.

- CHANGELOG
- src/Path/Include.hs
- test/Common.hs
- test/ValidityTest.hs
1) Breaking - Change the return type of `fileExtension` to throw an exception when there is no extension
2) Now all the extension operations can be expressed elegantly in terms of simple laws, all of them verified by property tests. `addExtension` and `splitExtension` are the basic operations and the rest are just convenient and trivial applications of these two. `addExtension` and `splitExtension` are lawful inverses of each other with this change.
> Expose splitExtension operation

- src/Path/Include.hs
I broke this in my previous change, the tests did not catch this, need to add tests to catch the broken case. But before I do that, let's first resolve this comment from my previous PR:
Another point that I am considering is that since we are re-introducing `replaceExtension` why not just drop this API. The is a bit awkward to explain (or non-intuitive) API since it can either REPLACE an extension or SET an extension and I am not sure how much useful it is in practice to warrant a place in the library. Anyway, now it is trivial to implement using other primitives if anyone really needs something like this, it is just:
```
addExtension ".ext" (maybe f fst $ splitExtension f)
```
> Fix replaceExtension or just drop it?

- CHANGELOG
- src/Path/Include.hs
- test/Windows.hs
Fixes #81
In this PR:
* Added path separator de-duplication when normalizing paths on Windows, and at the tail of the drive.
* On Posix, it still de-dupes consecutive slashes at the beginning of the path as before.
* Added check in `parseRelDir` that path is not all path separators (that's an absolute path on Posix and Windows).
* Removed test that asserted success when parsing `~/` on Windows as that's not a Windows thing.
* Changed a couple of relative dir path examples from successful to failing for paths that start with separators as that makes them absolute paths.
* Added handling of UNC (`\\host\share`) and Unicode (`\\?\C:\`) paths on Windows and tests for these types of paths
> Fixed FIXMEs in Windows tests

- src/Path/Include.hs
Following #140 PR, it misses the export of the data constructor. Otherwise there is not much we can do with `SomeBase`.
> Export SomeBase data constructor

- path.cabal
- src/Path/Internal.hs
- test/TH.hs
- test/Windows.hs
Provided a path of type `Path a b` we use the `Typeable` instances of
`a` and `b` to insert the correct type in the splice.
> Fixes #159

- .github/workflows/ci.yaml
- CHANGELOG
- path.cabal
- stack.yaml
- stack.yaml.lock
- test/Path/Gen.hs
- test/ValidityTest.hs
This change simplifies the validity-based testing and adds support for `genvalidity >= 1.0.0.0`.
I'll leave this here for a few days. If there is no pushback, and CI passes, then I'll go ahead and merge it.
> Support for genvalidity >=1.0.0.0

- src/Path/Include.hs
As I describe in https://github.com/commercialhaskell/path/issues/186, this would enable `Path Rel Dir`, `Path Rel File`, and so on, to also be instances of `Data`, which enables any other data type that uses `Path` as part of its structure to also easily derive `Data`.
> Make Rel, Abs, File and Dir instances of Data
